### ISSUE TITLE
Example of using iView with Meteor  ?

### ISSUE THREAD

**Issue by tomvolek** [ejfrancis/meteor-iview#3]
I am both new to Vue and iView. I already have a meteor app but cant seem to figure out how to use iView components like a table.  

Is is possible someone post a example of usage of iview with meteor please ?

**Comment by lunafi-evan** [comment]
hey @tomvolek 

All you've go to do is import the package and use it with Vue like below. The css should be bundled with your app by default.

```js
import iView from 'meteor/efrancis:iview';
import Vue from 'vue';

Meteor.startup(() => {
  Vue.use(iView);
});
```

**Comment by ejfrancis** [comment]
hey @tomvolek 

All you've go to do is import the package and use it with Vue like below. The css should be bundled with your app by default.

```js
import iView from 'meteor/efrancis:iview';
import Vue from 'vue';

Meteor.startup(() => {
  Vue.use(iView);
});
```

I have an example app integrating Vue w/Meteor that uses this package, you can look at that for full examples https://github.com/ejfrancis/Meteor-Vue-Modular-App-Starter

**Comment by tomvolek** [comment]
thanks ,  that was very helpful .
